version: '3.5'

x-display-env:
  &display-env
  DISPLAY: unix${DISPLAY}
  XAUTHORITY: /tmp/.docker.xauth

services:

  proj:
    build: .
    image: cv_proj
    container_name: cv-proj
    volumes:
      - ./app:/app
    environment:
      << : *display-env
    working_dir: /app
    tty: true
    command: [bash]

  lab:
    build:
      context: .
      dockerfile: lab.Dockerfile
    image: cv_proj_lab
    container_name: cv-proj-lab
    environment:
      << : *display-env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ./app:/home/jovyan/work
    ports:
      - 8888:8888
    command: [start.sh, jupyter, lab, --LabApp.token='']
