version: '3.5'

services:

  proj:
    build:
      context: .
      dockerfile: Dockerfile
    image: cv_proj_lab
    container_name: cv-proj-lab
    environment:
      DISPLAY: unix${DISPLAY}
      XAUTHORITY: /tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ./app:/home/jovyan/work
    ports:
      - 8888:8888
    command: [start.sh, jupyter, lab, --LabApp.token='']
